#!/bin/bash

sudo apt install zsh -y

# Alacritty
# WSL installation instructions found here: https://github.com/alacritty/alacritty/tree/master#installation

# Tmux
sudo apt install tmux -y

# NeoVim
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt-get update -y
sudo apt-get install neovim -y

# Oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# hostctl
TEMP_DEB="$(mktemp)" &&
wget -O "$TEMP_DEB" 'https://github.com/guumaster/hostctl/releases/download/v1.1.3/hostctl_1.1.3_linux_amd64.deb' &&
sudo dpkg -i "$TEMP_DEB"
rm -f "$TEMP_DEB"
