#!/usr/local/bin/zsh

# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Alacritty
brew install alacritty

# Tmux
brew install tmux

# NeoVim
brew install neovim

# hostctl
brew install guumaster/tap/hostctl

# terraform-ls (terraform language server)
brew install hashicorp/tap/terraform-ls

# install common linux settings
$HOME/.config/install_linux_common

