#!/usr/local/bin/zsh

# Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Alacritty
brew install alacritty

# Tmux
brew install tmux

# NeoVim
brew install neovim

# hostctl
brew install guumaster/tap/hostctl

# install common linux settings
self_dir=${0:a}
$self_dir/install_linux_common

