#!/bin/bash

sudo apt install zsh -y

# Alacritty
# WSL installation instructions found here: https://github.com/alacritty/alacritty/tree/master#installation

# Tmux
sudo apt install tmux -y
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# NeoVim
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt-get update -y
sudo apt-get install neovim -y

# hostctl
TEMP_DEB="$(mktemp)" &&
wget -O "$TEMP_DEB" 'https://github.com/guumaster/hostctl/releases/download/v1.1.3/hostctl_1.1.3_linux_amd64.deb' &&
sudo dpkg -i "$TEMP_DEB"
rm -f "$TEMP_DEB"

# install common linux settings
self_dir=${0:a}
$self_dir/install_linux_common

